# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import relay_pb2 as relay__pb2
except ImportError:
    import relay_pb2 as relay__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in relay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelayStub(object):
    """Bridge is the only RPC bb-relay exposes. Both the robot and the GPU worker
    open a bidirectional stream and the relay splices them together once both
    sides have arrived for the same session_id.

    The relay never parses RelayFrame.payload. The robot and the GPU put any
    bytes they want in there (in practice, serialized LeRobot AsyncInference
    messages). session_id and stream_id let the relay do its job: pair the
    two sides, and leave a seam for future per-session multiplexing inside one
    GPU connection (batched inference).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bridge = channel.stream_stream(
                '/bb.relay.v1.Relay/Bridge',
                request_serializer=relay__pb2.RelayFrame.SerializeToString,
                response_deserializer=relay__pb2.RelayFrame.FromString,
                _registered_method=True)


class RelayServicer(object):
    """Bridge is the only RPC bb-relay exposes. Both the robot and the GPU worker
    open a bidirectional stream and the relay splices them together once both
    sides have arrived for the same session_id.

    The relay never parses RelayFrame.payload. The robot and the GPU put any
    bytes they want in there (in practice, serialized LeRobot AsyncInference
    messages). session_id and stream_id let the relay do its job: pair the
    two sides, and leave a seam for future per-session multiplexing inside one
    GPU connection (batched inference).
    """

    def Bridge(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bridge': grpc.stream_stream_rpc_method_handler(
                    servicer.Bridge,
                    request_deserializer=relay__pb2.RelayFrame.FromString,
                    response_serializer=relay__pb2.RelayFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bb.relay.v1.Relay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bb.relay.v1.Relay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Relay(object):
    """Bridge is the only RPC bb-relay exposes. Both the robot and the GPU worker
    open a bidirectional stream and the relay splices them together once both
    sides have arrived for the same session_id.

    The relay never parses RelayFrame.payload. The robot and the GPU put any
    bytes they want in there (in practice, serialized LeRobot AsyncInference
    messages). session_id and stream_id let the relay do its job: pair the
    two sides, and leave a seam for future per-session multiplexing inside one
    GPU connection (batched inference).
    """

    @staticmethod
    def Bridge(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/bb.relay.v1.Relay/Bridge',
            relay__pb2.RelayFrame.SerializeToString,
            relay__pb2.RelayFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
